### ISSUE TITLE
Multiple select field not working

### ISSUE THREAD

**Issue by FaustineLarmagna** [nicolasbeauvais/Walrus#65]
I am using this in my form.yml : 

```
members:
  type: select
  multiple: true
  options:
    - email1
    - email2
    - email3
```

And in my controller I rewrite the options with setFieldValue('members', 'options', $array)
With $array containing email as keys and values.

When I select 2 or more elements in the list (in the select field) with ctrl+clic and I var_dump($_POST('members') I get : 

string 'example@gmail.com' (length=17)

I expected an array with the multiple values, I am doing it wrong ?

Also, I don't get the purpose of those two properties : 

class: myClass
data-name: myName

Regards.
